// Actual receiver dashboard UI with synthetic API responses. No production receiver is contacted.
const { chromium } = require(process.env.BACKUPDUCK_PLAYWRIGHT || 'playwright');
const http = require('http'), fs = require('fs'), path = require('path'), assert = require('assert');
const root=path.resolve(__dirname,'..');
const out=path.join(root,'build/design-review/browser');fs.mkdirSync(out,{recursive:true});
const items=Array.from({length:67},(_,i)=>({id:`fixture-${i}`, filename:`${['旅行','海边','生日','日常'][i%4]}_${String(i+1).padStart(3,'0')}.${i%3===1?'mp4':'heic'}`,kind:['motion','video','photo'][i%3],burst_primary:i%9===8?true:null,total_bytes:8540000+i*10000,confirmed_bytes:i%4===3?2150000:8540000+i*10000,receipt:i%4===3?'receiving':'received',processing:['complete','complete','failed','pending'][i%4],processing_error:i%4===2?'conversion_required':null,captured_at_ms:1790906400000-i*14400000,received_at_ms:1790934400000,published_at_ms:i%4<2?1790938400000:null,originals_released:false,senders:['旅行用 iPhone']}));
let lastRetry=null;
const server=http.createServer((req,res)=>{const u=new URL(req.url,'http://local');if(u.pathname.startsWith('/api/')){res.setHeader('Content-Type','application/json');if(u.pathname==='/api/login')return res.end(JSON.stringify({token:'synthetic-review-token'}));if(u.pathname==='/api/retry'){lastRetry=u.searchParams.get('id'); return res.end(JSON.stringify({count:lastRetry?1:17}));}if(u.pathname==='/api/overview')return res.end(JSON.stringify({total:67,received:50,published:34,failed:17,waiting:0,reserved_bytes:632000000,free_bytes:28500000000,min_free_bytes:3000000000,total_space_bytes:64000000000,device:{temperature_deci_celsius:385,battery_percent:78,charging:true,thermal_threshold_celsius:42,thermal_enabled:true,thermal_held:false}}));if(u.pathname==='/api/history'){let rows=items.filter(x=>!u.searchParams.get('search')||x.filename.toLowerCase().includes(u.searchParams.get('search').toLowerCase()));const st=u.searchParams.get('state'),k=u.searchParams.get('kind');rows=rows.filter(x=>!st||st==='all'||st==='receiving'&&x.receipt!=='received'||st==='published'&&x.processing==='complete'||st==='failed'&&x.processing==='failed'||st==='processing'&&x.receipt==='received'&&x.processing==='pending').filter(x=>!k||k==='all'||x.kind===k||k==='burst'&&x.burst_primary!=null);const p=Number(u.searchParams.get('page'))||1,n=Number(u.searchParams.get('per_page'))||20;return res.end(JSON.stringify({items:rows.slice((p-1)*n,p*n),total:rows.length,pages:Math.max(1,Math.ceil(rows.length/n)),page:p,per_page:n}));}res.statusCode=404;return res.end('{}');}
const files={'/':'crates/native/src/dashboard/index.html','/style.css':'crates/native/src/dashboard/style.css','/tokens.css':'crates/native/src/dashboard/tokens.css','/app.js':'crates/native/src/dashboard/app.js','/duck.png':'assets/AppIcon.png'};if(!files[u.pathname]){res.statusCode=404;return res.end();}res.setHeader('Content-Type',u.pathname.endsWith('.css')?'text/css':u.pathname.endsWith('.js')?'text/javascript':u.pathname.endsWith('.png')?'image/png':'text/html');res.end(fs.readFileSync(path.join(root,files[u.pathname])));});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({channel:'chrome',headless:true});try{for(const theme of ['light','dark']){const context=await browser.newContext({locale:'zh-CN',colorScheme:theme,viewport:{width:1360,height:920}});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(`http://127.0.0.1:${server.address().port}/`);await page.locator('#code').fill('1111111111');await page.locator('#login-button').click();await page.locator('#recent-items tr').first().waitFor();await page.screenshot({path:path.join(out,`overview-${theme}.png`)});for(const section of ['transfers','storage','settings']){await page.locator(`.side-link[data-page="${section}"]`).click();await page.locator(`[data-page-panel="${section}"]`).waitFor({state:'visible'});await page.screenshot({path:path.join(out,`${section}-${theme}.png`)});}await page.locator('.side-link[data-page="transfers"]').click();await page.locator('#pagination button').filter({hasText:/^2$/}).click();await page.waitForFunction(()=>document.getElementById('page-summary').textContent.includes('第 2'));await page.locator('#search-files').fill('生日');await page.waitForFunction(()=>document.querySelectorAll('#items tr').length===17);assert((await page.locator('#page-summary').textContent()).includes('第 1'));await page.locator('#items .file-name').first().click();await page.locator('#details-dialog').waitFor({state:'visible'});await page.screenshot({path:path.join(out,`detail-${theme}.png`)});await page.locator('#detail-retry').click();assert(lastRetry);await page.locator('#details-dialog').waitFor({state:'hidden'});assert.deepStrictEqual(errors,[]);await context.close();}const mobile=await browser.newContext({locale:'en-US',viewport:{width:390,height:844}});const p=await mobile.newPage();await p.goto(`http://127.0.0.1:${server.address().port}/`);await p.screenshot({path:path.join(out,'login-mobile.png')});await mobile.close();console.log('PASS: actual dashboard UI, 4 pages, light/dark, filename search, page reset and scoped retry. Screenshots use synthetic API data.');}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exit(1)});
