/* Design-only state machine. No fetch, uploads, device access, or persistent credentials. */
'use strict';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const $=s=>document.querySelector(s);
const navs=[['receive','接收','device'],['transfers','传输','transfer'],['storage','存储','drive'],['settings','设置','settings']];
const review=new URLSearchParams(location.search);
let route=catalog.some(x=>x.id===review.get('screen'))?review.get('screen'):'receive', scenario='', stack=[], tab='receive', filter='全部', message='', messageTimer;
const model={browser:true,restore:true,thermal:true,threshold:40,conversion:false,relay:false,automatic:false,theme:'跟随系统',language:'简体中文',name:'Pixel XL',code:'',codeError:'',formError:'',deviceEnabled:true,busy:false};
const info=id=>catalog.find(x=>x.id===id);
const openButton=(text,id,style='')=>`<button class="button ${style}" data-open="${id}">${esc(text)}</button>`;
const act=(text,action,style='')=>`<button class="button ${style}" data-do="${action}" ${model.busy?'disabled':''}>${esc(text)}</button>`;
const link=(text,id)=>`<button class="link" data-open="${id}">${esc(text)}${icon('chevron')}</button>`;
const group=(title,rows)=>`<div class="group">${title?`<div class="group-title">${esc(title)}</div>`:''}${rows}</div>`;
const setting=(title,note='',target='',value='',ic='')=>`<${target?'button':'div'} class="setting" ${target?`data-open="${target}"`:''}>${ic?icon(ic):''}<div class="grow"><strong>${esc(title)}</strong>${note?`<p>${esc(note)}</p>`:''}</div>${value?`<span class="value">${esc(value)}</span>`:target?icon('chevron'):''}</${target?'button':'div'}>`;
const switchRow=(title,note,key)=>`<div class="setting"><div class="grow"><strong>${esc(title)}</strong><p>${esc(note)}</p></div><button class="switch ${model[key]?'on':''}" role="switch" aria-label="${esc(title)}" aria-checked="${model[key]}" data-toggle="${key}" ${model.busy?'disabled':''}></button></div>`;
const note=(title,body='',kind='')=>`<div class="notice ${kind}">${icon(kind==='error'||kind==='warning'?'alert':'info')}<div class="grow"><strong>${esc(title)}</strong>${body?`<p>${esc(body)}</p>`:''}</div></div>`;
const pill=(text,kind='',ic='')=>`<span class="pill ${kind}">${ic?icon(ic):''}${esc(text)}</span>`;
const field=(label,key,value,type='text',error='')=>`<label class="field">${esc(label)}<input id="field-${key}" data-edit="${key}" type="${type}" ${key==='code'?'inputmode="numeric" maxlength="10" autocomplete="off"':''} value="${esc(value)}" class="${error?'invalid':''}" aria-invalid="${!!error}" ${error?`aria-describedby="error-${key}"`:''}>${error?`<span id="error-${key}" class="error" role="alert">${esc(error)}</span>`:''}</label>`;
const choices=(rows,key,current)=>group('',rows.map(([v,label])=>`<button class="setting" data-choice="${key}" data-value="${v}"><div class="grow"><strong>${esc(label)}</strong></div>${current===v?pill('已选','active','check'):''}</button>`).join(''));
const select=(label,key,values,current)=>`<label class="field">${esc(label)}<select data-edit="${key}">${values.map(v=>`<option ${String(v)===String(current)?'selected':''}>${v}</option>`).join('')}</select></label>`;
const failure=(text='未能保存，请重试。')=>note('操作未完成',text,'error')+act('重试','retry');
const busy=()=>note(model.busy?'正在保存…':'设置不会立即改变现有备份任务。');
const readings=(values)=>`<div class="readings">${values.map(([v,t])=>`<div>${esc(v)}<small>${esc(t)}</small></div>`).join('')}</div>`;
const files=Array.from({length:22},(_,i)=>({name:`IMG_${5442-i}.${i%4===2?'MOV':'HEIC'}`,type:i%4===2?'视频 · 00:18':i%3?'照片':'实况',time:`10/02 12:${59-i}`,state:i<2?'failed':i<5?'active':i<7?'waiting':'saved'}));
const states={failed:['相册处理失败','alert'],active:['接收中','transfer'],waiting:['已接收 · 待处理','clock'],saved:['已保存到相册','check']};
function fileRow(f){return `<button class="file" data-open="file-detail"><div class="thumb">${f.type.includes('视频')?icon('play'):''}</div><div class="grow"><strong>${f.name}</strong><p>${f.time} · ${f.type}</p></div>${pill(states[f.state][0],f.state,states[f.state][1])}</button>`}
function actions(...items){return items.join('')}
function content(id) {
 const failed=/失败|不可用|无法|无效|不兼容|账号改变|超时|中断/.test(scenario), running=/中|等待相册|等待降温/.test(scenario);
 switch(id) {
 case 'receive':{const empty=scenario==='首次使用', thermal=scenario==='高温暂停',paused=scenario==='手动暂停';return `<div class="hero"><div class="row"><div class="art ${empty?'brand':''}">${empty?'<img src="../../assets/AppIcon.png" alt="">':icon('device')}</div><div class="grow"><h2>${empty?'准备连接设备':thermal?'等待手机降温':paused?'接收已暂停':scenario==='已保存'?'已保存到 Pixel 相册':'正在接收'}</h2><p>${model.name} · ${empty?'尚未开始接收':'同一 Wi‑Fi'}</p></div>${pill(empty?'未启动':thermal||paused?'暂停':'在线',thermal?'waiting':'')}</div>${openButton('连接新设备','pairing','full '+(empty?'primary':''))}</div>${scenario==='启动失败'?note('接收无法启动','Wi‑Fi 地址不可用。检查网络后再试。','error')+link('查看连接帮助','help-connection'):thermal?note('接收已自动暂停','电池温度 43 °C，降至 38 °C 且系统热保护解除后继续。','warning'):''}${empty?`<h3>怎么配对？</h3>${group('',setting('连接 iPhone / iPad','显示配对码，让 iPhone 扫描','pair-code','','qr')+setting('连接 Mac','用 Pixel 扫描 Mac 的配对码','pair-scan','','scan'))}${note('选择连接方式后，会自动启动接收服务。')}`:`<div class="row"><h3 class="grow">接收概况</h3>${link('全部记录','transfers')}</div>${readings([['240','已保存'],['6','进行中'],['2','失败']])}${files.slice(2,5).map(fileRow).join('')}${act(paused?'继续新接收':'暂停新接收',paused?'resume':'pause')}`}${readings([[thermal?'43.0 °C':'37.2 °C','电池温度'],['22.4 GB','可用空间'],['78%','电量 · 充电中']])}${note('云端由 Google 相册继续备份','保存到 Pixel 相册不代表云端备份完成。')}`;}
 case 'pairing':return `<p>选择发送设备。接收服务会自动启动。</p>${scenario==='启动失败'?failure('Wi‑Fi 地址不可用，请检查网络。'):scenario==='启动中'?note('正在启动接收服务…','准备完成后显示配对步骤。'):group('',setting('连接 iPhone / iPad','显示配对码','pair-code','','qr')+setting('连接 Mac','扫描 Mac 配对码','pair-scan','','scan'))}`;
 case 'pair-code':return scenario==='失败'?failure('暂时无法生成配对码。'):scenario==='接收不可用'?note('接收服务暂不可用','恢复接收后刷新配对码。','warning')+act('刷新配对码','pair-refresh','primary'): `<p>保持两台设备连接同一 Wi‑Fi，用 iPhone 备份鸭扫描。</p><div class="demo-qr"><strong>演示 · 无效码</strong></div><p>Pixel 配对码使用当前接收身份；接收地址改变后需刷新。Mac 的邀请有效期由真实协议处理。</p>${act('刷新配对码','pair-refresh')}${act('模拟配对成功','pair-success','full primary')}`;
 case 'pair-scan':return `<div class="camera-demo">${icon('scan')}</div><h3>扫描 Mac 上的配对码</h3><p>在 Mac“接收设备”中显示配对码，放入取景框。</p>${scenario==='相机权限'?note('需要相机权限','仅用于扫描配对码。')+openButton('允许相机访问','system-permission','primary'):scenario==='无效码'?failure('该二维码不是有效的备份鸭配对码。'):scenario==='配对成功'?note('配对成功','返回接收页即可接收备份。')+openButton('返回接收','receive','primary'):act('模拟识别配对码','pair-success','primary')}`;
 case 'transfers':return scenario==='空白'?`<div class="empty"><div class="art brand"><img src="../../assets/AppIcon.png" alt=""></div><h2>还没有传输记录</h2><p>开始一次备份后，可查看传输与相册处理结果。</p>${openButton('连接新设备','pairing','primary full')}</div>`:scenario==='加载中'?note('正在读取本机记录…','缩略图与列表位置保持稳定。'): `<div class="row"><p class="grow">248 个项目 · 240 个已保存</p>${link('状态说明','status-guide')}</div><div class="chips">${['全部','进行中','失败','已保存'].map(v=>`<button class="chip ${filter===v?'active':''}" data-filter="${v}">${v}</button>`).join('')}</div>${files.filter(f=>filter==='全部'||filter==='失败'&&f.state==='failed'||filter==='已保存'&&f.state==='saved'||filter==='进行中'&&['active','waiting'].includes(f.state)).map(fileRow).join('')}`;
 case 'filters':return group('',setting('媒体类型','按照片、实况、视频或连拍筛选','filter-kind','全部')+setting('来源设备','按发送设备筛选','filter-sender','全部'))+act('刷新记录','refresh')+act('重试失败处理','retry-batch');
 case 'filter-kind':return choices(['全部','照片','实况','视频','连拍'].map(x=>[x,x]),'kind','全部');
 case 'filter-sender':return scenario==='空白'?note('还没有来源设备记录。'):choices(['全部','示例 iPhone','示例 Mac'].map(x=>[x,x]),'sender','全部');
 case 'status-guide':return group('',Object.entries(states).map(([s,[text,ic]])=>setting(text,{failed:'原件保留，可查看原因并重试。',active:'字节传输尚未完成。',waiting:'原件已校验，等待加入相册。',saved:'已加入 Pixel 系统相册。'}[s],'','',ic)).join(''))+note('这些状态不等于云端已备份','请在 Google 相册中确认云端结果。');
 case 'file-detail':{let stage=scenario==='失败'?'failed':scenario==='接收中'?'active':scenario==='待处理'?'waiting':'saved';return `<div class="preview"></div><div class="row"><h2 class="grow">IMG_5442.HEIC</h2>${pill(states[stage][0],stage)}</div><dl class="definitions">${[['类型','实况'],['拍摄时间',scenario==='时间缺失'?'未提供':'2026/10/02 12:59'],['来源设备','示例 iPhone'],['大小','12.6 MB'],['原件',scenario==='原件已释放'?'已按保留策略释放':stage==='active'?'尚未接收完成':'保留在 Pixel，可重试处理']].map(([k,v])=>`<div><dt>${k}</dt><dd>${v}</dd></div>`).join('')}</dl><ul class="timeline"><li class="${stage==='active'?'pending':''}">${stage==='active'?'正在接收原件':'原件已接收并校验'}<p>${stage==='active'?'尚未完成':'10/02 13:03'}</p></li><li class="${stage==='saved'?'':'pending'}">${states[stage][0]}<p>${stage==='failed'?'输入结构需要兼容转换，原件未删除':stage==='saved'?'10/02 13:04':'保存尚未完成'}</p></li><li class="pending">Google 相册云端<p>备份鸭不能读取该状态，请在 Google 相册确认。</p></li></ul>${stage==='failed'?note('怎么处理？','先重试；仍失败时查看原因，再决定是否开启兼容转换。','error')+act('重试处理','retry-file','primary')+link('兼容转换说明','conversion'):''}${stage==='saved'?openButton('在 Google 相册查看','system-gallery'):''}`;}
 case 'storage':return `<h2>${scenario==='空间不足'?'空间不足，接收已暂停':'空间足够，备份安心。'}</h2><p>${model.name} · 本机存储</p>${scenario==='读取失败'?failure('本机空间统计未能读取。'): `<div class="space"><strong>可用空间</strong><div class="amount">${scenario==='空间不足'?'1.2':'22.4'} GB <small>/ 64 GB</small></div><div class="meter"><span style="width:65%"></span></div><p>● 备份鸭原件 11.5 GB</p><p>● 相册副本与未完成文件 5.1 GB</p><p>● 其他 25.0 GB</p></div>`}${group('文件保留',setting('保留原件','相册处理失败时可从原件重试','retention',model.relay?'自动回收':'安全保留')+setting('空间限制','达到限制后暂停接收','storage-limits','16 GB')+setting('待处理文件','2 个文件相册处理失败','transfers','2 个'))}${note('清理前请确认云端备份','相册处理成功不等于云端备份。请保留来源原件。','warning')}${openButton('查看存储明细','storage-detail','full')}`;
 case 'storage-detail':return scenario==='读取失败'?failure('存储统计暂不可用。'):group('',setting('已保留原件','11.5 GB · 可供处理重试')+setting('未接收完成','328 MB')+setting('Pixel 相册副本','4.8 GB · 240 个项目')+setting('空间限制','16 GB 上限 · 3 GB 最低可用空间','storage-limits')+setting('检查历史原件','校验相册副本后预览可回收范围','relay-history')+setting('导出原件','导出并校验后，可选择回收中转原件','archive')+setting('打开 Google 相册','','system-gallery'))+note('统计可能与系统空间存在更新时间差。');
 case 'storage-limits':return `<p>达到上限或低于预留空间时，暂停新接收，不自动删除原件。</p>${select('原件空间上限','budget',['2 GB','4 GB','6 GB','10 GB','16 GB','32 GB','64 GB','128 GB'],'16 GB')}${select('最低可用空间','reserve',['0 GB','1 GB','2 GB','3 GB','5 GB','10 GB'],'3 GB')}${scenario==='保存失败'?failure():busy()}`;
 case 'retention':return group('',switchRow('自动回收中转原件','相册副本校验通过后回收应用内原件。','relay'))+note('请保留来源原件','此策略不验证 Google 相册云端备份，也不删除 Pixel 相册副本。','warning')+openButton('选择自动回收范围','relay-scope')+link('检查历史原件','relay-history')+(failed?failure():'');
 case 'relay-scope':return `<p>开启自动回收前，选择它影响的接收记录。</p>${choices([['new','仅回收新原件'],['history','同时回收历史']],'relayScope',model.relayScope||'new')}${note('历史原件也需重新验证','缺少、变化或无法校验的相册副本，其原件继续保留。','warning')}${failed?failure():busy()}`;
 case 'relay-history':return `<h2>${scenario==='等待降温'?'等待手机降温':scenario==='已取消'?'检查已取消':'检查历史原件'}</h2>${failed?failure('检查未能完成，剩余原件保留。'):note(scenario==='等待降温'?'暂停检查，可取消。':scenario==='已取消'?'尚未回收任何原件。':'已检查 128 项','接收和自动回收关闭时，也可主动检查。')}${openButton('查看模拟检查结果','relay-preview','primary full')}${act('取消检查','cancel-job')}`;
 case 'relay-preview':return `<h2>${scenario==='无可回收项'?'没有可回收原件':'可回收 120 项 · 1.8 GB'}</h2>${group('',setting('继续保留','4 项缺少校验记录')+setting('相册副本已变化','2 项')+setting('相册副本缺失','2 项'))}${note('只回收应用内中转原件','保留系统相册、配对和接收记录。本次不会开启自动回收；不确认云端备份。','warning')}${scenario==='无可回收项'?'':openButton('回收已验证原件','relay-reclaim','primary full')}`;
 case 'relay-reclaim':return `<p>回收前会再次打开相册副本并校验。预计释放 1.8 GB，变化或无法校验的原件继续保留。</p>${running?note('正在重新校验并回收…','可停止后续回收，已回收部分无法撤销。'):failed?failure('剩余原件继续保留。'):note('此操作不删除 Pixel 相册照片，也不确认云端备份。','请确认来源原件仍在。','warning')}`;
 case 'relay-result':return note(scenario==='已取消'?'回收已取消':'已回收 118 项 · 1.7 GB',scenario==='部分保留'?'2 项发生变化，原件继续保留。':'系统相册与接收记录保留。')+openButton('返回存储','storage','full');
 case 'archive':return `<p>将应用内中转原件与清单导出为 ZIP，完成后重新读取并校验。选择目标位置后开始。</p>${note('导出不会删除原件','校验通过后，再单独选择是否回收。')}`;
 case 'archive-progress':return failed?failure('导出未完成，应用内原件保留。'):scenario==='没有原件'?note('没有可导出的原件。'):scenario==='已取消'?note('导出已取消','目标位置可能留下未完成文件，应用内原件保留。'):note(scenario==='校验中'?'正在校验导出文件…':'正在导出原件…','请保持目标存储位置可访问。')+openButton('查看模拟校验结果','archive-result','primary full')+act('取消导出','cancel-job');
 case 'archive-result':return scenario==='校验失败'?failure('导出文件不完整，原件未回收。'):note('导出已通过校验','128 项原件已导出。')+openButton('保留应用内原件','storage','full')+openButton('回收已导出原件','archive-reclaim','full');
 case 'archive-reclaim':return `<p>再次校验 ZIP 后，回收这 128 项应用内原件。Pixel 相册照片与接收记录保留。</p>${failed?failure('导出文件校验失败，原件继续保留。'):running?note('正在校验并回收…'):note('请确认导出文件保存位置可靠。','','warning')}`;
 case 'settings':return `<p>接收与保存的方式，由你决定。</p>${group('接收设置',switchRow('重启后自动接收','重新打开备份鸭时恢复接收。','restore')+setting('温度保护','超过电池温度阈值，暂停新的接收','thermal',model.thermal?model.threshold+' °C':'关闭')+setting('兼容转换','原样封装不支持时才使用，可重新编码','conversion',model.conversion?'开启':'关闭'))}${group('浏览器管理',setting('浏览器管理','在电脑查看和管理这台 Pixel','browser',model.browser?'开启':'关闭'))}${group('设备与外观',setting('设备名称','','device-name',model.name)+setting('发送设备','查看配对记录与接收权限','devices')+setting('外观','','appearance',model.theme)+setting('语言','','language',model.language))}${group('帮助与关于',setting('使用帮助','','help')+setting('应用更新','当前版本 0.2.0-rc.3','updates')+setting('诊断与实验','','diagnostics')+setting('备份鸭 / BackupDuck','让回忆安心抵达。'))}`;
 case 'thermal':return `<p>使用 Pixel 电池传感器读数。系统热保护也会影响接收。</p>${group('',switchRow('温度保护','关闭后不按此温度阈值暂停。','thermal'))}${choices(Array.from({length:11},(_,i)=>[String(i+35),(i+35)+' °C'+(i+35===40?'（默认）':'')]),'threshold',String(model.threshold))}${note('自动恢复','温度低于暂停阈值 2 °C，且系统热保护解除后继续。')}${failed?failure():''}`;
 case 'conversion':return group('',switchRow('允许兼容转换','仅在直接封装明确不支持输入结构时转换。','conversion'))+note('优先保留原图、视频和音频','关闭时，需要转换的文件会处理失败并保留原件，可稍后重试。')+note('云端“正在准备”不会触发转换。');
 case 'browser':return `<p>在可信任的同一 Wi‑Fi 上，用电脑管理这台 Pixel。</p>${group('',switchRow('允许浏览器管理','关闭后浏览器无法访问，不影响设备配对。','browser')+setting('访问管理页','查看地址和访问码','browser-access')+setting('设置访问码','重启和升级后保持不变','browser-code')+setting('退出所有浏览器','撤销现有登录，不修改访问码','browser-revoke'))}${scenario==='启动中'?note('正在开启浏览器管理…'):scenario==='启动失败'?failure('接收服务暂不可用，先检查连接。'):note('仅在可信任的局域网使用','当前管理服务使用 HTTP。')}${scenario==='接收未启动'?note('请先开启接收，并启用浏览器管理。')+act('开始接收','browser-ready','primary full'):''}`;
 case 'browser-access':return scenario==='接收未启动'?note('接收服务尚未启动','启动后才能获得可访问的管理地址。','warning')+act('启动接收服务','browser-start','primary'):scenario==='地址不可用'?failure('Wi‑Fi 地址暂不可用，请检查网络后重试。'): `<p>在电脑浏览器输入地址，再使用访问码登录。</p>${group('',setting('管理地址','http://192.0.2.10:8485（演示）')+setting('访问码','0000000000（演示，无效）'))}${act('复制管理地址','copy-address','primary full')}${note('不要向不信任的人分享访问码','访问码和浏览器登录，与发送设备配对独立。')}`;
 case 'browser-code':return `<p>访问码在重启和升级后保持不变。保存后所有浏览器需要重新登录，不影响发送设备配对。</p>${field('新的 10 位数字访问码','code',model.code,'password',model.codeError|| (scenario==='输入错误'?'请输入 10 位数字。':''))}${model.formError||scenario==='保存失败'?failure('保存未完成，原访问码仍有效。'):busy()}${openButton('重置为随机访问码','browser-reset','full')}`;
 case 'browser-reset':return `<p>生成新的随机访问码，并让所有浏览器退出登录？新码可在“访问管理页”查看。</p>${model.formError||failed?failure('重置未完成，原访问码仍有效。'):running||model.busy?note('正在重置…'):note('不会改变设备配对和备份任务。')}`;
 case 'browser-revoke':return `<p>撤销所有浏览器的登录？访问码、发送设备配对和备份任务保持不变。</p>${model.formError||failed?failure('撤销未完成，请重试。'):running||model.busy?note('正在撤销登录…'):note('下次访问需要重新输入访问码。')}`;
 case 'device-name':return `<p>此名称会显示在配对与设备页面。</p>${field('设备名称','nameDraft',model.nameDraft??model.name,'text',scenario==='名称无效'?'名称不能为空，且最多 64 个字符。':'')}${failed?failure():busy()}`;
 case 'devices':return scenario==='空白'?note('还没有发送设备','配对后会显示在这里。')+openButton('连接新设备','pairing','primary full'):failed?failure('设备记录未能读取。'):group('',setting('示例 iPhone','iPhone · 最近连接 10/02 13:04','device-detail','允许接收','device')+setting('示例 Mac','Mac · 最近连接 10/01 18:00','device-detail','允许接收','laptop'));
 case 'device-detail':return group('',setting('设备名称','示例 iPhone')+setting('设备类型','iPhone')+setting('最近地址','192.0.2.20（演示）')+setting('最近连接','10/02 13:04'))+note('禁用后不接受此发送端的新请求','不删除接收记录或照片。')+openButton(scenario==='已禁用'?'允许接收':'禁用此设备','device-confirm','full');
 case 'device-confirm':return `<p>更改此发送设备的接收权限？接收记录和已保存文件不会删除。</p>${failed?failure():running?note('正在保存…'):''}`;
 case 'appearance':return choices(['跟随系统','浅色','深色'].map(x=>[x,x]),'theme',model.theme);
 case 'language':return choices(['跟随系统','简体中文','English'].map(x=>[x,x]),'language',model.language);
 case 'help':return `<p>了解连接、后台接收、结果与原件管理。</p>${group('',setting('连接与配对','同一网络、权限、接收地址','help-connection')+setting('后台接收','锁屏、后台限制、自动恢复','help-background')+setting('接收与保存','原件、Pixel 相册和云端的区别','help-results')+setting('空间与原件','保留、回收和导出','help-storage')+setting('失败恢复','重试、诊断与更新','help-recovery'))}`;
 case 'help-connection':return note('当前接收地址',scenario==='未启动'?'启动接收后可查看。':failed?'暂时无法读取。':'192.0.2.10:8484（演示）')+group('',setting('同一 Wi‑Fi','两台设备需处于可互通的局域网。VPN 应允许局域网连接。')+setting('配对方向','iPhone 扫 Pixel 的码；Pixel 扫 Mac 的码。','pairing')+setting('启动失败','端口冲突或 Wi‑Fi 地址不可用时，按具体原因恢复。'));
 case 'help-background':return group('',setting('后台持续接收','接收运行时显示系统通知。系统省电限制可能中断后台任务。')+setting('自动恢复','重启或重新打开应用时，按自动接收设置恢复。','settings')+setting('发送端限制','iPhone 后台运行时间受系统限制，大批传输宜保持应用前台。'));
 case 'help-results':return group('',setting('已接收','原件已持久保存并校验。')+setting('已保存到相册','已加入 Pixel 系统相册。')+setting('Google 相册云端','云端由 Google 相册上传，备份鸭不能证明云端成功。','system-gallery'));
 case 'help-storage':return group('',setting('空间限制','原件上限与最低可用空间共同限制新接收。','storage-limits')+setting('保留原件','失败可从原件重试。','retention')+setting('自动回收','验证系统相册副本后回收中转原件，不验证云端。','retention')+setting('导出原件','导出通过校验后才能选择回收。','archive'));
 case 'help-recovery':return group('',setting('重试相册处理','先查看失败原因，重试请求不代表立即成功。','transfers')+setting('导出诊断','附发生时间和设备状态，报告不含照片内容或访问码。','export-report')+setting('应用更新','签名不兼容时不要直接卸载或清除存储。','updates'));
 case 'updates':return group('',setting('当前版本','0.2.0-rc.3（演示）')+switchRow('自动检查更新','每天最多自动检查一次。','automatic'))+note({检查中:'正在检查更新…',最新版:'已是最新版',可更新:'可更新至 0.2.0-rc.4',检查失败:'检查失败，请检查网络后重试。',下载中:'正在下载更新…',下载失败:'下载未完成，请重试。',安装权限:'请允许此应用安装更新。',签名不兼容:'安装包签名与现有应用不同。',开发版本:'当前是验证版本，无法直接安装正式包。'}[scenario],scenario==='签名不兼容'?'不要卸载或清除存储，先保留原件和记录。':'',failed?'error':'')+actions(act(scenario==='可更新'?'下载更新':'检查更新','update-check','primary full'),scenario==='安装权限'?openButton('打开安装权限','system-install','full'):'',link('官方网站','system-website'));
 case 'diagnostics':return group('',setting('发送设备','','devices')+setting('日志保留','','log-limits')+setting('导出诊断日志','','export-report')+setting('导出相册记录','','export-report')+setting('实验功能','释放空间与相册页面检查','experiments')+setting('停止接收服务','与暂停新接收不同','stop-receiving'));
 case 'log-limits':return `<p>只管理运行日志，不删除照片、接收记录或配对。</p>${select('日志保留天数','logDays',['1 天','7 天','14 天','30 天','90 天'],'14 天')}${select('最大日志条目','logLimit',['1000','5000','10000','20000'],'10000')}${failed?failure():busy()}`;
 case 'export-report':return group('',setting('诊断日志','阶段、任务标识与字节数等事件，不含照片或凭据')+setting('相册记录','保存文件名、校验与时间，不含照片内容')+setting('检查报告','Google 相册页面检查观察结果'))+(scenario==='导出失败'?failure('报告未能写入所选位置。'):scenario==='导出中'?note('正在导出报告…'):scenario==='导出成功'?note('报告已导出','分享前可先查看报告内容。'):openButton('选择保存位置','system-document','primary full'));
 case 'experiments':return `<p>这些功能依赖 Google 相册页面和 Android 无障碍能力，默认关闭。</p>${group('',setting('自动释放空间','让 Google 相册释放已确认备份的设备副本','cleanup')+setting('Google 相册页面检查','观察官方释放空间流程','photos-diagnostics'))}`;
 case 'cleanup':return note({未授权:'尚未开启无障碍服务',未绑定:'请先绑定 Google 相册账号',就绪:'账号已绑定，可按需执行',运行中:'正在检查释放空间',结果待核对:'等待 Google 相册结果',账号改变:'相册账号已改变，已停止清理'}[scenario],scenario==='结果待核对'?'不重复点击释放；需核对后恢复传输。':'',scenario==='账号改变'?'error':'')+group('',setting('无障碍权限','只使用经你授权的相册页面操作','cleanup-disclosure')+setting('绑定当前账号','本机仅保存账号指纹','cleanup-bind')+switchRow('空间不足时自动释放','只在绑定账号并授权后开启。','automatic'))+openButton(scenario==='结果待核对'?'检查清理结果':'释放空间','cleanup-progress','primary full')+link('手动核对后结束等待','cleanup-review')+link('相册页面检查','photos-diagnostics');
 case 'cleanup-disclosure':return `<p>仅在 Google 相册官方确认内容已安全备份时操作“释放空间”。可能影响此设备其他应用的已备份照片。</p><p>不点击删除，不清空云端回收站。本机只保存账号指纹；不保存或发送账号原文、截图、照片标签。</p><p>默认关闭，每轮最多 5 分钟；需要手机解锁。可随时停止或关闭系统无障碍服务，结果不明时不重复释放。</p>`;
 case 'cleanup-bind':return note(scenario==='已绑定'?'账号已绑定':scenario==='需要解锁'?'请先解锁手机':scenario==='无法识别'?'无法识别账号，已停止':'正在核对当前 Google 相册账号',scenario==='无法识别'?'请打开 Google 相册首页后重试。':'本机保存账号指纹，不显示或保存账号原文。',failed?'error':'')+openButton('打开 Google 相册','system-gallery','full')+act('模拟绑定成功','bind-success','full primary');
 case 'cleanup-progress':return note({运行中:'正在核对账号与释放空间入口…',等待相册:'等待 Google 相册完成',已完成:'Google 相册已报告释放完成',没有可释放文件:'Google 相册没有可释放设备文件',页面无法识别:'无法识别页面，已停止点击',需要解锁:'请解锁手机后继续',超时:'本轮检查已超时',已停止:'检查已停止'}[scenario],scenario==='等待相册'?'新接收暂时暂停，不重复点击释放。':'原件管理仍按保留策略执行。',failed?'error':'')+act('停止检查','cancel-job')+openButton('已手动核对','cleanup-review','full');
 case 'cleanup-review':return `<p>请先在 Google 相册核对结果。确认后只恢复备份鸭传输，不删除文件，也不证明云端备份完成。自动清理会等待 15 分钟再尝试。</p>`;
 case 'photos-diagnostics':return note({未授权:'尚未开启无障碍服务',就绪:'准备开始页面检查',检查中:'正在观察 Google 相册页面',已完成:'页面检查已结束',超时:'检查已超时',中断:'检查已中断'}[scenario], '观察结果不等于逐张照片的云端备份回执。',failed?'error':'')+group('',setting('Google 相册版本','演示版本')+setting('已观察阶段',scenario==='已完成'?'账号入口、确认、释放完成':'尚无完整观察记录'))+openButton('开启权限 / 查看授权','probe-disclosure','full')+act('开始检查','probe-start','full primary')+act('停止检查','cancel-job')+link('导出检查报告','export-report');
 case 'probe-disclosure':return `<p>使用无障碍服务观察 Google 相册官方页面，不读取照片内容，不保存账号、屏幕截图或照片标签。</p><p>请按引导自行操作 Google 相册；观察结果只用于排查界面兼容性，不代表逐张云端备份确认。</p>`;
 case 'stop-receiving':return `<p>停止局域网接收服务？新的发送请求和浏览器管理将无法连接。已接收原件与备份记录保留，已接收文件的相册处理继续按既有任务运行。</p>`;
 case 'system-website':case 'system-permission':case 'system-document':case 'system-install':case 'system-accessibility':case 'system-gallery':{const data={ 'system-website':['外部浏览器','打开备份鸭官方网站。浏览器返回不改变更新、接收或配对状态。','updates'],'system-permission':['Android 系统权限','系统显示通知 / 相机权限。允许后回到请求流程，拒绝后保留解释和再次进入入口。','pair-scan'],'system-document':['Android 文件选择器','选择 ZIP 或报告保存位置。取消返回原页面，未开始导出；写入失败保留原件。','archive-progress'],'system-install':['Android 安装 / 外部网站','系统安装权限与安装确认由 Android 提供。取消后保留已下载文件；签名不兼容不提示卸载。','updates'],'system-accessibility':['Android 无障碍设置','Android 显示系统服务授权。返回后重新检查权限，未授权时不开启实验操作。','cleanup'],'system-gallery':['Google 相册','外部应用自行显示照片与云端结果。返回后不把打开相册当作云端成功。','receive']}[id];return `<div class="system-boundary"><h2>${data[0]}</h2><p>${data[1]}</p><p>系统 / 外部应用边界，无自定义仿制界面。</p></div>${scenario==='失败'||scenario==='未安装'?note('无法打开','返回应用后显示原因和重试入口。','error'):''}${act('模拟返回应用','system-return','primary full')}${act('取消 / 返回','back','full')}`;}
 case 'components':return `<div class="component-samples"><h3>图标与导航</h3><p>24 × 24 坐标，统一 1.7 描边；视觉 22dp、命中 48dp。</p><div class="row">${['info','device','transfer','drive','settings','more'].map(n=>`<button class="icon-btn" aria-label="${n}">${icon(n)}</button>`).join('')}</div><h3>按钮</h3>${act('主要操作','example','primary full')}${act('次要操作','example','full')}<h3>设置行</h3>${group('',setting('设置名称','辅助说明，与控制分开','appearance','跟随系统')+switchRow('开启功能','保存失败时恢复原值。','thermal'))}<h3>状态</h3><div class="chips">${Object.entries(states).map(([k,[t,ic]])=>pill(t,k,ic)).join('')}</div><h3>反馈</h3>${note('说明','无需操作的信息。')}${note('需要注意','附下一步入口。','warning')}${note('操作未完成','重要失败保留在当前页面。','error')}${act('展示短提示','example')}<h3>弹层与确认</h3>${openButton('输入表单','browser-code','full')}${openButton('确认操作','browser-revoke','full')}${openButton('长任务','relay-history','full')}</div>`;
 default:throw Error('Missing screen contract: '+id);
 }
}
function footer(id){switch(id){case 'browser-code':return act(model.busy?'保存中…':'保存访问码','save-code','primary');case 'browser-reset':return actions(act('取消','back'),act(model.busy?'重置中…':'重置访问码','reset-code','primary'));case 'browser-revoke':return actions(act('取消','back'),act(model.busy?'处理中…':'退出所有浏览器','revoke','danger'));case 'device-name':case 'storage-limits':case 'log-limits':case 'relay-scope':return actions(act('取消','back'),act(model.busy?'保存中…':'保存','save','primary'));case 'device-confirm':return actions(act('取消','back'),act('确认更改','device-change','primary'));case 'relay-reclaim':return actions(act('取消','back'),openButton('开始模拟回收','relay-result','danger'));case 'archive':return actions(act('取消','back'),openButton('选择导出位置','system-document','primary'));case 'archive-reclaim':return actions(act('保留原件','back'),act('模拟回收完成','archive-done','danger'));case 'cleanup-disclosure':case 'probe-disclosure':return actions(act('取消','back'),openButton('同意并打开系统设置','system-accessibility','primary'));case 'cleanup-review':return actions(act('取消','back'),act('确认已核对','cleanup-reviewed','primary'));case 'stop-receiving':return actions(act('取消','back'),act('停止服务','stop','danger'));default:return '';}}
function navigate(id){if(!info(id))throw Error('Unknown design destination: '+id);stack.push({route,scenario,tab});route=id;scenario=info(id).states[0];if(id==='device-name')model.nameDraft=model.name;model.codeError='';model.formError='';model.busy=false;if(navs.some(x=>x[0]===id))tab=id;render()}
function back(){const prev=stack.pop();if(prev){({route,scenario,tab}=prev)}else{route=tab;scenario=info(route).states[0]}model.busy=false;model.formError='';render()}
function frame(id){const main=navs.some(x=>x[0]===id);return `<div class="toolbar">${main?'':`<button class="icon-btn" data-do="back" aria-label="返回">${icon('back')}</button>`}<h1>${esc(info(id).title)}</h1>${id==='receive'?`<button class="icon-btn" data-open="help" aria-label="使用帮助">${icon('info')}</button>`:id==='transfers'?`<button class="icon-btn" data-open="filters" aria-label="筛选与更多">${icon('more')}</button>`:''}</div><div class="content" data-screen="${id}">${content(id)}</div>${id==='transfers'?`<div class="activity">${icon(scenario==='高温暂停'?'heat':'transfer')}<div class="grow"><strong>${scenario==='高温暂停'?'Pixel 正在降温':scenario==='失败'?'2 个文件未保存到相册':'正在从 iPhone 接收'}</strong><p>${scenario==='高温暂停'?'43 °C · 降温后继续':scenario==='失败'?'原件保留，可查看原因':'4 个文件进行中 · 12.8 MB/s'}</p></div><div class="meter"><span style="width:${scenario==='失败'?0:60}%"></span></div></div>`:''}${main?`<nav class="nav" aria-label="应用导航">${navs.map(([id,t,ic])=>`<button data-tab="${id}" class="${tab===id?'active':''}"><span class="symbol">${icon(ic)}</span><label>${t}</label></button>`).join('')}</nav>`:''}`;}
function render(){const spec=info(route);if(!scenario)scenario=spec.states[0];$('#scenario').innerHTML=spec.states.map(x=>`<option ${x===scenario?'selected':''}>${esc(x)}</option>`).join('');let markup;if(['sheet','confirm'].includes(spec.kind)){const under=stack.slice().reverse().find(x=>['page','review','system'].includes(info(x.route).kind))?.route||'settings';const originalScenario=scenario;scenario=info(under).states[0];markup=frame(under);scenario=originalScenario;const confirm=spec.kind==='confirm';markup+=`<div class="${confirm?'confirm-mask':'sheet-mask'}" data-dismiss="true"><section class="${confirm?'confirm':'sheet'}" role="dialog" aria-modal="true" aria-labelledby="dialog-title">${confirm?`<h2 id="dialog-title">${spec.title}</h2>`:`<div class="handle"></div><div class="sheet-head"><h2 id="dialog-title">${spec.title}</h2><button class="icon-btn" data-do="back" aria-label="关闭">${icon('close')}</button></div>`}<div class="content" data-screen="${route}">${content(route)}</div>${footer(route)?`<div class="sheet-foot">${footer(route)}</div>`:''}</section></div>`}else markup=frame(route);$('#app').innerHTML=markup+(message?`<div class="snackbar" role="status">${esc(message)}<button class="link" data-do="dismiss-message">关闭</button></div>`:'');if(['sheet','confirm'].includes(spec.kind)){[...$('#app').children].filter(x=>!x.matches('.sheet-mask,.confirm-mask,.snackbar')).forEach(x=>x.inert=true)}$('#catalog').innerHTML=catalog.filter(x=>x.title.includes($('#search').value)).map(x=>`<button data-open="${x.id}" class="${route===x.id?'selected':''}">${x.title}<small>${x.id} · ${x.kind}</small></button>`).join('');$('#contract').innerHTML=`<div class="contract"><strong>${spec.id} · ${spec.title}</strong><p>来源：${spec.source} / ${spec.symbol}<br>呈现：${spec.kind} · 原生进度：${spec.native}<br>模拟状态：${spec.states.join(' / ')}</p><p>原型反馈不代表真实处理或云端上传结果。</p></div>`;document.documentElement.dataset.screen=route;}
function toast(text){message=text;render();clearTimeout(messageTimer);messageTimer=setTimeout(()=>{message='';render()},3500)}
function save(kind){const id=route;const fail=scenario.includes('失败');if(id==='device-name'&&(!model.nameDraft?.trim()||[...model.nameDraft].length>40)){scenario='名称无效';render();return}if(kind==='save-code'&&!/^[0-9]{10}$/.test(model.code)){model.codeError='请输入 10 位数字。';render();$('#field-code')?.focus();return}model.busy=true;model.formError='';render();setTimeout(()=>{if(route!==id)return;model.busy=false;if(fail){model.formError='保存未完成，原设置仍有效。';render()}else{if(kind==='save-code')model.code='';if(id==='device-name')model.name=model.nameDraft.trim();if(kind==='save'&&id==='relay-scope')model.relay=true;back();toast(kind==='revoke'?'已退出所有浏览器。':kind==='reset-code'?'访问码已重置，浏览器需重新登录。':'已保存。')}},700)}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(b&&!b.disabled){if(model.busy)return;if(b.dataset.open){navigate(b.dataset.open);return}if(b.dataset.tab){stack=[];route=tab=b.dataset.tab;scenario=info(route).states[0];render();return}if(b.dataset.toggle){const key=b.dataset.toggle;if(key==='relay'&&!model.relay){navigate('relay-scope');return}if(key==='automatic'&&route==='cleanup'&&!model.automatic){navigate('cleanup-disclosure');return}model[key]=!model[key];render();return}if(b.dataset.choice){const key=b.dataset.choice;model[key]=key==='threshold'?Number(b.dataset.value):b.dataset.value;if(key==='theme'&&model.theme!=='跟随系统')document.documentElement.dataset.theme=model.theme==='深色'?'dark':'light';if(!['relayScope','threshold'].includes(key))back();else render();return}const a=b.dataset.do;switch(a){case 'back':back();break;case 'system-return':{const origin=stack.at(-1)?.route;if(route==='system-document'){back();if(origin==='archive')navigate('archive-progress');else{scenario='导出中';render()}}else if(route==='system-accessibility'){back();navigate(origin==='probe-disclosure'?'photos-diagnostics':'cleanup')}else back();break;}case 'copy-address':toast('管理地址已复制（演示）。');break;case 'save-code':case 'save':case 'reset-code':case 'revoke':save(a);break;case 'retry':model.formError='';scenario=info(route).states[0];render();break;case 'pair-success':stack=[];route=tab='receive';scenario='接收中';render();toast('配对成功（演示）。');break;case 'pair-refresh':scenario='有效';render();break;case 'pause':scenario='手动暂停';render();break;case 'resume':scenario='接收中';render();break;case 'retry-file':toast('已请求重试，成功前仍保留失败状态。');break;case 'retry-batch':toast('已请求重试失败处理。');break;case 'refresh':toast('记录已刷新，筛选与滚动位置保留（演示）。');break;case 'browser-start':model.browser=true;scenario='可访问';render();break;case 'browser-ready':model.browser=true;scenario='已开启';render();break;case 'device-change':model.deviceEnabled=!model.deviceEnabled;back();toast('接收权限已保存（演示）。');break;case 'bind-success':route='cleanup';scenario='就绪';render();break;case 'probe-start':scenario='检查中';render();break;case 'cleanup-reviewed':back();scenario='就绪';render();toast('已按手动核对结束等待。');break;case 'archive-done':back();toast('已回收导出校验通过的中转原件（演示）。');break;case 'stop':stack=[];route=tab='receive';scenario='首次使用';render();break;case 'cancel-job':scenario=info(route).states.find(x=>x.includes('取消')||x.includes('停止'))||info(route).states[0];render();toast('后续任务已取消，已有文件保留。');break;case 'update-check':scenario=scenario==='可更新'?'下载中':'检查中';render();break;case 'example':toast('短提示：请求已提交。');break;case 'dismiss-message':message='';render();break;default:if(b.dataset.filter){filter=b.dataset.filter;render()}}}if(e.target.dataset.dismiss==='true'&&!model.busy)back()});
document.addEventListener('input',e=>{if(e.target.dataset.edit)model[e.target.dataset.edit]=e.target.value;if(e.target.id==='search')render()});
function applyScenario(){if(route==='browser')model.browser=scenario!=='未开启';if(route==='thermal')model.thermal=scenario!=='保护关闭'}
$('#theme').onclick=()=>{const dark=document.documentElement.dataset.theme!=='dark';document.documentElement.dataset.theme=dark?'dark':'light';$('#theme').textContent=dark?'切换浅色':'切换深色'};$('#width').onchange=e=>{$('#phone').style.width=e.target.value+'px';$('#phone').style.height=e.target.value==='320'?'640px':'720px'};$('#font').onchange=e=>{$('#phone').style.setProperty('--font',e.target.value);$('#phone').dataset.large=Number(e.target.value)>1.3};$('#motion').onchange=e=>$('#phone').classList.toggle('reduced',e.target.checked);$('#components').onclick=()=>navigate('components');$('#scenario').onchange=e=>{scenario=e.target.value;applyScenario();model.busy=/保存中|处理中/.test(scenario);model.formError='';model.codeError='';render()};
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!model.busy){back();return}if(e.key==='Tab'){const modal=$('[role=dialog]');if(!modal)return;const list=[...modal.querySelectorAll('button,input,select')].filter(x=>!x.disabled);if(e.shiftKey&&document.activeElement===list[0]){e.preventDefault();list.at(-1)?.focus()}else if(!e.shiftKey&&document.activeElement===list.at(-1)){e.preventDefault();list[0]?.focus()}}});
window.reviewAPI={open:id=>navigate(id),setScenario:value=>{scenario=value;applyScenario();model.busy=/保存中|处理中/.test(value);render()},catalog};
render();
