// Generated by scripts/export-design-tokens.py; edit tokens.json instead.
import SwiftUI
#if os(macOS)
import AppKit
#else
import UIKit
#endif
enum DuckColors {
  static let canvas = adaptive(light: (0.960784, 0.952941, 0.933333), dark: (0.074510, 0.098039, 0.133333))
  static let surface = adaptive(light: (1.000000, 1.000000, 1.000000), dark: (0.113725, 0.149020, 0.200000))
  static let subtle = adaptive(light: (0.964706, 0.968627, 0.976471), dark: (0.141176, 0.180392, 0.239216))
  static let text = adaptive(light: (0.125490, 0.172549, 0.243137), dark: (0.937255, 0.952941, 0.972549))
  static let textSecondary = adaptive(light: (0.400000, 0.443137, 0.517647), dark: (0.666667, 0.713725, 0.776471))
  static let border = adaptive(light: (0.890196, 0.905882, 0.925490), dark: (0.211765, 0.262745, 0.329412))
  static let action = adaptive(light: (0.086275, 0.364706, 0.807843), dark: (0.549020, 0.725490, 1.000000))
  static let actionBackground = adaptive(light: (0.917647, 0.945098, 0.988235), dark: (0.141176, 0.235294, 0.376471))
  static let brandAccent = adaptive(light: (0.960784, 0.772549, 0.203922), dark: (0.960784, 0.807843, 0.333333))
  static let saved = adaptive(light: (0.098039, 0.454902, 0.298039), dark: (0.537255, 0.847059, 0.666667))
  static let savedBackground = adaptive(light: (0.917647, 0.960784, 0.933333), dark: (0.129412, 0.247059, 0.196078))
  static let attention = adaptive(light: (0.572549, 0.368627, 0.047059), dark: (0.964706, 0.800000, 0.505882))
  static let attentionBackground = adaptive(light: (1.000000, 0.960784, 0.874510), dark: (0.270588, 0.215686, 0.141176))
  static let failure = adaptive(light: (0.698039, 0.231373, 0.231373), dark: (1.000000, 0.678431, 0.678431))
  static let failureBackground = adaptive(light: (0.988235, 0.933333, 0.933333), dark: (0.282353, 0.172549, 0.196078))
  static let brandAccentBackground = adaptive(light: (1.000000, 0.968627, 0.839216), dark: (0.239216, 0.203922, 0.125490))
  private static func adaptive(light: (Double, Double, Double), dark: (Double, Double, Double)) -> Color {
    #if os(macOS)
    return Color(nsColor: NSColor(name: nil) { appearance in
      let c = appearance.bestMatch(from: [.darkAqua, .aqua]) == .darkAqua ? dark : light
      return NSColor(srgbRed: c.0, green: c.1, blue: c.2, alpha: 1)
    })
    #else
    return Color(uiColor: UIColor { traits in
      let c = traits.userInterfaceStyle == .dark ? dark : light
      return UIColor(red: c.0, green: c.1, blue: c.2, alpha: 1)
    })
    #endif
  }
}
