#!/usr/bin/env python3
"""Generate native semantic colors from the approved design's single source."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TOKENS = json.loads((ROOT / "design/backupduck-v1/tokens.json").read_text())
outputs = {}
swift = ['// Generated by scripts/export-design-tokens.py; edit tokens.json instead.',
         'import SwiftUI', '#if os(macOS)', 'import AppKit', '#else', 'import UIKit', '#endif',
         'enum DuckColors {']
for name, light in TOKENS['colors']['light'].items():
    dark = TOKENS['colors']['dark'][name]
    def channels(value):
        return ', '.join(f'{int(value[i:i + 2], 16) / 255:.6f}' for i in (1, 3, 5))
    swift.append(f'  static let {name} = adaptive(light: ({channels(light)}), dark: ({channels(dark)}))')
swift += ['  private static func adaptive(light: (Double, Double, Double), dark: (Double, Double, Double)) -> Color {',
          '    #if os(macOS)',
          '    return Color(nsColor: NSColor(name: nil) { appearance in',
          '      let c = appearance.bestMatch(from: [.darkAqua, .aqua]) == .darkAqua ? dark : light',
          '      return NSColor(srgbRed: c.0, green: c.1, blue: c.2, alpha: 1)',
          '    })', '    #else', '    return Color(uiColor: UIColor { traits in',
          '      let c = traits.userInterfaceStyle == .dark ? dark : light',
          '      return UIColor(red: c.0, green: c.1, blue: c.2, alpha: 1)',
          '    })', '    #endif', '  }', '}']
outputs['apps/apple/Shared/DuckColors.swift'] = '\n'.join(swift) + '\n'
import re
for theme, directory in [('light', 'values'), ('dark', 'values-night')]:
    xml = ['<!-- Generated from design/backupduck-v1/tokens.json. -->', '<resources>']
    for name, value in TOKENS['colors'][theme].items():
        snake = re.sub(r'(?<!^)(?=[A-Z])', '_', name).lower()
        xml.append(f'    <color name="duck_{snake}">{value}</color>')
    outputs[f'apps/android/app/src/main/res/{directory}/duck_colors.xml'] = '\n'.join(xml + ['</resources>']) + '\n'
css = ['/* Generated from design/backupduck-v1/tokens.json. */']
for theme, selector in [('light', ':root'), ('dark', ':root[data-theme="dark"]')]:
    declarations = ';'.join(f'--duck-{re.sub(r"(?<!^)(?=[A-Z])", "-", k).lower()}:{v}' for k, v in TOKENS['colors'][theme].items())
    css.append(selector + '{color-scheme:' + theme + ';' + declarations + '}')
css.append('@media(prefers-color-scheme:dark){' + css[2].replace(':root[data-theme="dark"]', ':root:not([data-theme="light"])') + '}')
outputs['crates/native/src/dashboard/tokens.css'] = '\n'.join(css) + '\n'
check = argparse.ArgumentParser()
check.add_argument('--check', action='store_true')
args = check.parse_args()
stale = []
for name, content in outputs.items():
    file = ROOT / name
    if args.check:
        if not file.exists() or file.read_text() != content:
            stale.append(name)
    else:
        file.parent.mkdir(parents=True, exist_ok=True)
        file.write_text(content)
if stale:
    raise SystemExit('Stale design colors; run scripts/export-design-tokens.py: ' + ', '.join(stale))
print('Design colors verified.' if args.check else 'Exported Apple, Android and browser design colors.')
